
const translations = {
  "en": {
    "topbar": "Mallorca Launch Offer: your free custom website demo — no payment until you want to go live.",
    "nav_home": "Home",
    "nav_services": "Services",
    "nav_pricing": "Pricing",
    "nav_about": "About",
    "nav_contact": "Contact",
    "footer_line": "Websites with more presence, more clarity and less friction.",
    "footer_cta": "Ready when you are.",
    "footer_link": "Request your free demo",
    "home_eyebrow": "Webdesign for Mallorca",
    "home_h1": "First impressions decide.",
    "home_lead": "We create refined multilingual websites for ambitious local businesses — with a free custom demo before you pay a single euro.",
    "cta_free_demo": "Request your FREE Website Demo",
    "cta_prices": "See launch offer",
    "trust_1": "No upfront payment",
    "trust_2": "Ready within days",
    "trust_3": "Multilingual by default",
    "glass_small": "Free custom preview",
    "glass_big": "See it first. Pay later.",
    "why_eyebrow": "The offer",
    "why_h2": "We build the first impression before you make the decision.",
    "why_text": "Send us your business name, your current website or Instagram, and what you offer. We create a tailored preview. You only continue if it feels right.",
    "card1_h": "A demo made for you",
    "card1_p": "Not a template with your logo pasted on it. A first version shaped around your business, your market and your customers.",
    "card2_h": "Fast enough to matter",
    "card2_p": "Local businesses should not wait weeks for a better online presence. We keep the process lean, direct and clear.",
    "card3_h": "Fair from day one",
    "card3_p": "A clean launch price, an optional care plan and no pressure. You decide when the website is ready to go live.",
    "price_eyebrow": "Mallorca Launch Offer",
    "price_h2": "A premium start without the agency price.",
    "price_text": "Your website starts with a free custom demo. If you want to launch it, the current launch price is simple and transparent.",
    "price_label": "one-time setup",
    "cta_start": "Start with a free demo",
    "industry_eyebrow": "Built for local businesses",
    "industry_h2": "Restaurants, hotels, real estate, beauty, trades — and everything that needs to look better online.",
    "ind_restaurants": "Restaurants",
    "ind_hotels": "Hotels",
    "ind_realestate": "Real estate",
    "ind_beauty": "Beauty studios",
    "ind_vacation": "Vacation rentals",
    "ind_trades": "Trades & services",
    "ind_cafes": "Cafés & bars",
    "ind_fitness": "Fitness",
    "faq_eyebrow": "Questions",
    "faq_h2": "Simple answers. No hidden complications.",
    "faq1_q": "Do we really get a free demo first?",
    "faq1_a": "Yes. We create a custom first impression for your business. You pay only if you want to continue and publish it.",
    "faq2_q": "How fast can it go live?",
    "faq2_a": "Depending on content and feedback, many websites can be prepared within a few days.",
    "faq3_q": "Can we keep our own domain?",
    "faq3_a": "Yes. We can connect your existing domain or help you register a new one.",
    "faq4_q": "Can we take over the website ourselves?",
    "faq4_a": "Yes. We can hand over the files and give you clear instructions. Or you can choose the care plan and we handle the technical side.",
    "services_eyebrow": "Services",
    "services_h1": "Everything your website needs. Nothing it does not.",
    "services_lead": "We keep the process clear, fast and focused on what actually makes a business look better online.",
    "service1_h": "Website design",
    "service1_p": "A modern look, sharp structure and a first impression that feels intentional.",
    "service2_h": "Multilingual setup",
    "service2_p": "German, English and Spanish written to sound natural — not translated line by line.",
    "service3_h": "Mobile-first build",
    "service3_p": "Most people will find you on their phone. Your website should feel effortless there.",
    "service4_h": "Launch & care",
    "service4_p": "Domain help, hosting support, small updates and a clean handover if you prefer to manage it yourself.",
    "process_eyebrow": "Process",
    "process_h2": "From idea to online — without the usual back and forth.",
    "step1_h": "Send the basics",
    "step1_p": "Name, current links, services, colors and anything you like.",
    "step2_h": "Get your preview",
    "step2_p": "We create a free first version tailored to your business.",
    "step3_h": "Refine it",
    "step3_p": "We adjust the details until the direction feels right.",
    "step4_h": "Go live",
    "step4_p": "Only then do you pay and decide whether you want care or handover.",
    "pricing_eyebrow": "Pricing",
    "pricing_h1": "Clear prices. No agency fog.",
    "pricing_lead": "Start with a free custom demo. Pay only when you want to turn it into your live website.",
    "launch_offer": "Launch Offer",
    "setup_text": "one-time setup for your website launch",
    "setup_li1": "Custom website design",
    "setup_li2": "German / English / Spanish",
    "setup_li3": "Mobile-first layout",
    "setup_li4": "WhatsApp & contact integration",
    "setup_li5": "Basic SEO structure",
    "care_offer": "Optional Care",
    "care_text": "per month for businesses that want us to keep things simple",
    "care_li1": "Hosting support",
    "care_li2": "Small text changes",
    "care_li3": "Technical help",
    "care_li4": "Peace of mind",
    "cta_talk": "Talk to us",
    "handover_eyebrow": "Handover",
    "handover_h2": "Want to manage it yourself? No problem.",
    "handover_text": "If you prefer to take over the website, we can hand over the files and explain the next steps clearly. If you prefer not to touch the technical side, the care plan is there.",
    "about_eyebrow": "About CaPa",
    "about_h1": "Young enough to move fast. Serious enough to get it right.",
    "about_lead": "CaPa Webdesign was created for businesses that do not want a slow, complicated agency process — but still want a website that feels refined.",
    "about2_eyebrow": "Our angle",
    "about2_h2": "Less noise. More presence.",
    "about2_text": "We focus on the details that make a website feel premium: proportion, spacing, language, speed and the small moments that build trust.",
    "about3_text": "For Mallorca businesses, presentation matters. Your website is often the first place a guest, client or customer decides whether you feel professional.",
    "value1_h": "Fast",
    "value1_p": "Because momentum matters.",
    "value2_h": "Fair",
    "value2_p": "Because good design should be reachable.",
    "value3_h": "Focused",
    "value3_p": "Because a website should sell the next step, not explain everything.",
    "contact_eyebrow": "Contact",
    "contact_h1": "Send us your business. We send back a first impression.",
    "contact_lead": "Request your free custom website demo. No payment, no pressure, no obligation.",
    "cta_whatsapp": "Write on WhatsApp",
    "cta_email": "Send an email",
    "contact_card1_h": "What to send",
    "contact_li1": "Business name",
    "contact_li2": "Current website or Instagram",
    "contact_li3": "Your main services",
    "contact_li4": "Preferred language",
    "contact_li5": "Any style you like",
    "contact_card2_h": "Direct contact"
  },
  "de": {
    "topbar": "Mallorca Launch Angebot: kostenlose Website-Demo für dein Unternehmen — bezahlt wird erst, wenn du live gehen möchtest.",
    "nav_home": "Home",
    "nav_services": "Leistungen",
    "nav_pricing": "Preise",
    "nav_about": "Über uns",
    "nav_contact": "Kontakt",
    "footer_line": "Websites mit mehr Wirkung, mehr Klarheit und weniger Umwegen.",
    "footer_cta": "Bereit, wenn du es bist.",
    "footer_link": "Kostenlose Demo anfragen",
    "home_eyebrow": "Webdesign für Mallorca",
    "home_h1": "Der erste Eindruck entscheidet.",
    "home_lead": "Wir gestalten hochwertige mehrsprachige Websites für ambitionierte Unternehmen auf Mallorca — mit kostenloser individueller Demo, bevor ein einziger Euro bezahlt wird.",
    "cta_free_demo": "Kostenlose Website-Demo anfragen",
    "cta_prices": "Launch-Angebot ansehen",
    "trust_1": "Keine Vorkasse",
    "trust_2": "In wenigen Tagen bereit",
    "trust_3": "Mehrsprachig von Anfang an",
    "glass_small": "Kostenlose individuelle Vorschau",
    "glass_big": "Erst sehen. Dann entscheiden.",
    "why_eyebrow": "Das Angebot",
    "why_h2": "Wir bauen den ersten Eindruck, bevor du dich entscheidest.",
    "why_text": "Schick uns den Namen deines Unternehmens, deine aktuelle Website oder Instagram und kurz, was du anbietest. Wir erstellen eine passende Vorschau. Weiter geht es nur, wenn sie überzeugt.",
    "card1_h": "Eine Demo, die wirklich zu dir passt",
    "card1_p": "Keine Vorlage mit eingefügtem Logo. Eine erste Version, die sich an deinem Unternehmen, deinem Markt und deinen Kunden orientiert.",
    "card2_h": "Schnell genug, um etwas zu verändern",
    "card2_p": "Lokale Unternehmen sollten nicht wochenlang auf einen besseren Auftritt warten. Unser Prozess ist schlank, direkt und klar.",
    "card3_h": "Fair ab dem ersten Kontakt",
    "card3_p": "Ein klarer Launch-Preis, ein optionales Care-Programm und kein Druck. Du entscheidest, wann die Website live gehen soll.",
    "price_eyebrow": "Mallorca Launch Angebot",
    "price_h2": "Premium-Auftritt ohne Agenturpreise.",
    "price_text": "Der Start ist eine kostenlose individuelle Demo. Wenn du damit live gehen möchtest, bleibt der Preis einfach und transparent.",
    "price_label": "einmaliges Setup",
    "cta_start": "Mit kostenloser Demo starten",
    "industry_eyebrow": "Für lokale Unternehmen",
    "industry_h2": "Restaurants, Hotels, Immobilien, Beauty, Handwerk — und alle, die online besser wirken wollen.",
    "ind_restaurants": "Restaurants",
    "ind_hotels": "Hotels",
    "ind_realestate": "Immobilien",
    "ind_beauty": "Beauty Studios",
    "ind_vacation": "Ferienvermietungen",
    "ind_trades": "Handwerk & Services",
    "ind_cafes": "Cafés & Bars",
    "ind_fitness": "Fitness",
    "faq_eyebrow": "Fragen",
    "faq_h2": "Klare Antworten. Keine versteckten Umwege.",
    "faq1_q": "Bekommen wir wirklich zuerst eine kostenlose Demo?",
    "faq1_a": "Ja. Wir erstellen eine individuelle erste Vorschau für dein Unternehmen. Bezahlt wird erst, wenn du weitermachen und veröffentlichen möchtest.",
    "faq2_q": "Wie schnell kann die Website online sein?",
    "faq2_a": "Je nach Inhalt und Feedback können viele Websites innerhalb weniger Tage vorbereitet werden.",
    "faq3_q": "Können wir unsere eigene Domain behalten?",
    "faq3_a": "Ja. Wir können deine bestehende Domain verbinden oder beim Kauf einer neuen Domain helfen.",
    "faq4_q": "Können wir die Website später selbst übernehmen?",
    "faq4_a": "Ja. Wir können die Dateien übergeben und die nächsten Schritte klar erklären. Oder du nimmst das Care-Programm und wir kümmern uns um die Technik.",
    "services_eyebrow": "Leistungen",
    "services_h1": "Alles, was die Website braucht. Nichts, was sie unnötig macht.",
    "services_lead": "Wir halten den Prozess klar, schnell und fokussiert auf das, was ein Unternehmen online wirklich stärker wirken lässt.",
    "service1_h": "Website Design",
    "service1_p": "Ein moderner Auftritt, klare Struktur und ein erster Eindruck, der bewusst gestaltet wirkt.",
    "service2_h": "Mehrsprachiger Aufbau",
    "service2_p": "Deutsch, Englisch und Spanisch — so geschrieben, dass jede Sprache natürlich klingt und nicht übersetzt.",
    "service3_h": "Mobile-first Umsetzung",
    "service3_p": "Die meisten Menschen sehen deine Website zuerst am Handy. Genau dort muss sie leicht und hochwertig wirken.",
    "service4_h": "Launch & Betreuung",
    "service4_p": "Domain-Hilfe, Hosting-Support, kleine Änderungen und eine saubere Übergabe, wenn du selbst übernehmen möchtest.",
    "process_eyebrow": "Ablauf",
    "process_h2": "Von der Idee zur Website — ohne endloses Hin und Her.",
    "step1_h": "Basics senden",
    "step1_p": "Name, aktuelle Links, Leistungen, Farben und alles, was dir gefällt.",
    "step2_h": "Vorschau erhalten",
    "step2_p": "Wir erstellen eine kostenlose erste Version passend zu deinem Unternehmen.",
    "step3_h": "Feinschliff",
    "step3_p": "Wir passen die Details an, bis die Richtung stimmt.",
    "step4_h": "Live gehen",
    "step4_p": "Erst dann zahlst du und entscheidest, ob du Betreuung oder Übergabe möchtest.",
    "pricing_eyebrow": "Preise",
    "pricing_h1": "Klare Preise. Kein Agentur-Nebel.",
    "pricing_lead": "Starte mit einer kostenlosen individuellen Demo. Bezahlt wird erst, wenn daraus deine Live-Website werden soll.",
    "launch_offer": "Launch Angebot",
    "setup_text": "einmaliges Setup für deinen Website-Launch",
    "setup_li1": "Individuelles Website Design",
    "setup_li2": "Deutsch / Englisch / Spanisch",
    "setup_li3": "Mobile-first Layout",
    "setup_li4": "WhatsApp & Kontaktintegration",
    "setup_li5": "SEO-Grundstruktur",
    "care_offer": "Optionales Care-Programm",
    "care_text": "pro Monat für Unternehmen, die es einfach halten möchten",
    "care_li1": "Hosting-Support",
    "care_li2": "Kleine Textänderungen",
    "care_li3": "Technische Hilfe",
    "care_li4": "Ruhiger Kopf",
    "cta_talk": "Kontakt aufnehmen",
    "handover_eyebrow": "Übergabe",
    "handover_h2": "Du willst selbst übernehmen? Kein Problem.",
    "handover_text": "Wenn du die Website selbst verwalten möchtest, übergeben wir die Dateien und erklären die nächsten Schritte klar. Wenn du nichts mit Technik zu tun haben willst, gibt es das Care-Programm.",
    "about_eyebrow": "Über CaPa",
    "about_h1": "Jung genug, um schnell zu sein. Seriös genug, um sauber zu liefern.",
    "about_lead": "CaPa Webdesign ist für Unternehmen entstanden, die keinen langsamen, komplizierten Agenturprozess wollen — aber trotzdem einen Auftritt, der hochwertig wirkt.",
    "about2_eyebrow": "Unser Ansatz",
    "about2_h2": "Weniger Lärm. Mehr Wirkung.",
    "about2_text": "Wir achten auf die Details, die eine Website hochwertig wirken lassen: Proportion, Abstand, Sprache, Geschwindigkeit und kleine Momente, die Vertrauen schaffen.",
    "about3_text": "Für Unternehmen auf Mallorca zählt Präsentation. Die Website ist oft der erste Ort, an dem Gäste, Kunden oder Interessenten entscheiden, ob ein Unternehmen professionell wirkt.",
    "value1_h": "Schnell",
    "value1_p": "Weil Momentum zählt.",
    "value2_h": "Fair",
    "value2_p": "Weil gutes Design erreichbar sein sollte.",
    "value3_h": "Fokussiert",
    "value3_p": "Weil eine Website den nächsten Schritt verkaufen soll, nicht alles erklären.",
    "contact_eyebrow": "Kontakt",
    "contact_h1": "Schick uns dein Unternehmen. Wir schicken dir den ersten Eindruck.",
    "contact_lead": "Fordere deine kostenlose individuelle Website-Demo an. Keine Zahlung, kein Druck, keine Verpflichtung.",
    "cta_whatsapp": "Auf WhatsApp schreiben",
    "cta_email": "E-Mail senden",
    "contact_card1_h": "Was du senden kannst",
    "contact_li1": "Name des Unternehmens",
    "contact_li2": "Aktuelle Website oder Instagram",
    "contact_li3": "Deine wichtigsten Leistungen",
    "contact_li4": "Gewünschte Sprache",
    "contact_li5": "Stil, der dir gefällt",
    "contact_card2_h": "Direkter Kontakt"
  },
  "es": {
    "topbar": "Oferta de lanzamiento en Mallorca: demo web personalizada gratis — pagas solo si quieres publicarla.",
    "nav_home": "Inicio",
    "nav_services": "Servicios",
    "nav_pricing": "Precios",
    "nav_about": "Nosotros",
    "nav_contact": "Contacto",
    "footer_line": "Webs con más presencia, más claridad y menos fricción.",
    "footer_cta": "Cuando quieras, empezamos.",
    "footer_link": "Pedir demo gratis",
    "home_eyebrow": "Diseño web en Mallorca",
    "home_h1": "La primera impresión decide.",
    "home_lead": "Creamos webs multilingües, elegantes y rápidas para negocios con ambición en Mallorca — con una demo personalizada gratis antes de pagar nada.",
    "cta_free_demo": "Pide tu demo web GRATIS",
    "cta_prices": "Ver oferta de lanzamiento",
    "trust_1": "Sin pago por adelantado",
    "trust_2": "Lista en pocos días",
    "trust_3": "Multilingüe desde el principio",
    "glass_small": "Vista previa personalizada gratis",
    "glass_big": "Primero la ves. Luego decides.",
    "why_eyebrow": "La propuesta",
    "why_h2": "Creamos la primera impresión antes de que tomes la decisión.",
    "why_text": "Envíanos el nombre de tu negocio, tu web o Instagram actual y lo que ofreces. Preparamos una primera propuesta a medida. Sigues solo si te convence.",
    "card1_h": "Una demo pensada para tu negocio",
    "card1_p": "No una plantilla con tu logo encima. Una primera versión construida alrededor de tu marca, tu mercado y tus clientes.",
    "card2_h": "Rápidos de verdad",
    "card2_p": "Un negocio local no debería esperar semanas para verse mejor online. Nuestro proceso es directo, ligero y claro.",
    "card3_h": "Justo desde el principio",
    "card3_p": "Precio de lanzamiento claro, plan de cuidado opcional y cero presión. Tú decides cuándo la web está lista para publicarse.",
    "price_eyebrow": "Oferta de lanzamiento Mallorca",
    "price_h2": "Presencia premium sin precio de agencia.",
    "price_text": "Todo empieza con una demo personalizada gratis. Si quieres publicarla, el precio de lanzamiento es claro y directo.",
    "price_label": "setup único",
    "cta_start": "Empezar con demo gratis",
    "industry_eyebrow": "Para negocios locales",
    "industry_h2": "Restaurantes, hoteles, inmobiliarias, belleza, servicios — y cualquier negocio que quiera verse mejor online.",
    "ind_restaurants": "Restaurantes",
    "ind_hotels": "Hoteles",
    "ind_realestate": "Inmobiliarias",
    "ind_beauty": "Centros de belleza",
    "ind_vacation": "Alquiler vacacional",
    "ind_trades": "Servicios & oficios",
    "ind_cafes": "Cafés & bares",
    "ind_fitness": "Fitness",
    "faq_eyebrow": "Preguntas",
    "faq_h2": "Respuestas claras. Sin complicaciones ocultas.",
    "faq1_q": "¿De verdad recibimos una demo gratis primero?",
    "faq1_a": "Sí. Creamos una primera propuesta personalizada para tu negocio. Solo pagas si quieres continuar y publicarla.",
    "faq2_q": "¿Cuánto tarda en estar online?",
    "faq2_a": "Según el contenido y el feedback, muchas webs pueden prepararse en pocos días.",
    "faq3_q": "¿Podemos mantener nuestro dominio?",
    "faq3_a": "Sí. Podemos conectar tu dominio actual o ayudarte a registrar uno nuevo.",
    "faq4_q": "¿Podemos gestionar la web nosotros después?",
    "faq4_a": "Sí. Podemos entregarte los archivos y explicar los siguientes pasos. O puedes elegir el plan Care y nos ocupamos de la parte técnica.",
    "services_eyebrow": "Servicios",
    "services_h1": "Lo que tu web necesita. Nada que la haga pesada.",
    "services_lead": "Un proceso claro, rápido y enfocado en lo que realmente hace que un negocio se vea mejor online.",
    "service1_h": "Diseño web",
    "service1_p": "Una imagen actual, una estructura clara y una primera impresión que se siente cuidada.",
    "service2_h": "Web multilingüe",
    "service2_p": "Alemán, inglés y español escritos para sonar naturales — no traducidos palabra por palabra.",
    "service3_h": "Mobile-first",
    "service3_p": "La mayoría te verá desde el móvil. Ahí es donde tu web tiene que sentirse impecable.",
    "service4_h": "Lanzamiento & cuidado",
    "service4_p": "Ayuda con dominio, soporte de hosting, pequeños cambios y entrega clara si prefieres gestionarla tú.",
    "process_eyebrow": "Proceso",
    "process_h2": "De la idea a online — sin vueltas innecesarias.",
    "step1_h": "Envía lo básico",
    "step1_p": "Nombre, enlaces actuales, servicios, colores y referencias que te gusten.",
    "step2_h": "Recibe tu propuesta",
    "step2_p": "Creamos una primera versión gratuita pensada para tu negocio.",
    "step3_h": "Ajustamos",
    "step3_p": "Pulimos los detalles hasta que la dirección encaje.",
    "step4_h": "Publicamos",
    "step4_p": "Solo entonces pagas y eliges entre cuidado continuo o entrega.",
    "pricing_eyebrow": "Precios",
    "pricing_h1": "Precios claros. Sin humo de agencia.",
    "pricing_lead": "Empieza con una demo personalizada gratis. Pagas solo cuando quieres convertirla en tu web online.",
    "launch_offer": "Oferta de lanzamiento",
    "setup_text": "setup único para lanzar tu web",
    "setup_li1": "Diseño web personalizado",
    "setup_li2": "Alemán / Inglés / Español",
    "setup_li3": "Diseño pensado para móvil",
    "setup_li4": "Integración WhatsApp & contacto",
    "setup_li5": "Estructura SEO básica",
    "care_offer": "Care opcional",
    "care_text": "al mes para negocios que quieren mantenerlo fácil",
    "care_li1": "Soporte de hosting",
    "care_li2": "Pequeños cambios de texto",
    "care_li3": "Ayuda técnica",
    "care_li4": "Tranquilidad",
    "cta_talk": "Hablar con nosotros",
    "handover_eyebrow": "Entrega",
    "handover_h2": "¿Quieres gestionarla tú? Perfecto.",
    "handover_text": "Si prefieres quedarte con la web, te entregamos los archivos y te explicamos los pasos. Si no quieres tocar la parte técnica, existe el plan Care.",
    "about_eyebrow": "Sobre CaPa",
    "about_h1": "Jóvenes para movernos rápido. Serios para hacerlo bien.",
    "about_lead": "CaPa Webdesign nace para negocios que no quieren un proceso lento y complicado — pero sí una web con presencia y buen gusto.",
    "about2_eyebrow": "Nuestra forma",
    "about2_h2": "Menos ruido. Más presencia.",
    "about2_text": "Cuidamos los detalles que hacen que una web se sienta premium: proporción, espacio, lenguaje, velocidad y esos pequeños gestos que generan confianza.",
    "about3_text": "En Mallorca, la presentación importa. Tu web suele ser el primer lugar donde un cliente decide si tu negocio transmite profesionalidad.",
    "value1_h": "Rápidos",
    "value1_p": "Porque el impulso cuenta.",
    "value2_h": "Justos",
    "value2_p": "Porque el buen diseño debería estar al alcance.",
    "value3_h": "Enfocados",
    "value3_p": "Porque una web debe vender el siguiente paso, no explicarlo todo.",
    "contact_eyebrow": "Contacto",
    "contact_h1": "Envíanos tu negocio. Te devolvemos una primera impresión.",
    "contact_lead": "Pide tu demo web personalizada gratis. Sin pago, sin presión, sin compromiso.",
    "cta_whatsapp": "Escribir por WhatsApp",
    "cta_email": "Enviar email",
    "contact_card1_h": "Qué puedes enviar",
    "contact_li1": "Nombre del negocio",
    "contact_li2": "Web o Instagram actual",
    "contact_li3": "Servicios principales",
    "contact_li4": "Idioma preferido",
    "contact_li5": "Estilo que te guste",
    "contact_card2_h": "Contacto directo"
  }
};

function setLang(lang) {
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  localStorage.setItem("capa_lang", lang);
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) el.textContent = dict[key];
  });
  document.querySelectorAll("[data-lang]").forEach(btn => btn.classList.toggle("active", btn.dataset.lang === lang));
}

document.querySelectorAll("[data-lang]").forEach(btn => {
  btn.addEventListener("click", () => setLang(btn.dataset.lang));
});

const saved = localStorage.getItem("capa_lang") || "en";
setLang(saved);

const menuBtn = document.querySelector(".menu-btn");
const nav = document.querySelector(".main-nav");
if (menuBtn && nav) {
  menuBtn.addEventListener("click", () => nav.classList.toggle("open"));
}

const revealEls = document.querySelectorAll(".card, .split-section, .pricing-preview, .faq, .about-layout, .image-band, .process");
const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add("visible");
      observer.unobserve(entry.target);
    }
  });
}, { threshold: .12 });
revealEls.forEach(el => {
  el.style.opacity = "0";
  el.style.transform = "translateY(18px)";
  el.style.transition = "opacity .7s ease, transform .7s ease";
  observer.observe(el);
});
const style = document.createElement("style");
style.textContent = ".visible{opacity:1!important;transform:translateY(0)!important}";
document.head.appendChild(style);
